#!/bin/sh

# THIS SCRIPT IS FOR PROJECT MAINTAINER ONLY
# It is executed only to generate "configure"

set -x
if [ ! -d config ]; then mkdir config; fi
aclocal -I config
autoheader
automake --foreign --add-missing --copy
autoconf
