/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KVJava */

#ifndef _Included_KVJava
#define _Included_KVJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KVJava
 * Method:    getFrame
 * Signature: (Z)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_KVJava_getFrame (JNIEnv *, jobject,  jboolean) ;

/*
 * Class:     KVJava
 * Method:    putFrame
 * Signature: (Ljava/util/HashMap;)V
 */
JNIEXPORT void JNICALL Java_KVJava_putFrame (JNIEnv *, jobject, jobject);

/*
 * Class:     KVJava
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_KVJava_close (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
